INSERT INTO book (title, author, description, category, release_date, isborrowed) VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 'A novel set in the Jazz Age on Long Island, near New York City.', 'Fiction', '1925-04-10', false),
('To Kill a Mockingbird', 'Harper Lee', 'A novel about the racial injustice in the Deep South.', 'Fiction', '1960-07-11', false),
('1984', 'George Orwell', 'A dystopian novel about totalitarianism and surveillance.', 'Fiction', '1949-06-08', false),
('Moby-Dick', 'Herman Melville', 'A sailor’s quest to catch a giant whale named Moby Dick.', 'Adventure', '1851-11-14', false),
('Pride and Prejudice', 'Jane Austen', 'A story of love and social standing in early 19th century England.', 'Romance', '1813-01-28', false),
('The Catcher in the Rye', 'J.D. Salinger', 'A novel about the angst and alienation of adolescence.', 'Fiction', '1951-07-16', false),
('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic fantasy novel about the journey to destroy the One Ring.', 'Fantasy', '1954-07-29', false),
('Animal Farm', 'George Orwell', 'A satirical novel about a farm and its animal revolution.', 'Political Satire', '1945-08-17', false),
('Brave New World', 'Aldous Huxley', 'A dystopian novel about a society obsessed with happiness through technology and genetics.', 'Science Fiction', '1932-08-30', false),
('Crime and Punishment', 'Fyodor Dostoevsky', 'A philosophical novel about crime, guilt, and redemption.', 'Philosophy', '1866-01-01', false),
('The Hobbit', 'J.R.R. Tolkien', 'A fantasy novel that precedes The Lord of the Rings.', 'Fantasy', '1937-09-21', false),
('The Da Vinci Code', 'Dan Brown', 'A mystery thriller about religious conspiracies and hidden messages.', 'Mystery', '2003-03-18', true),
('Harry Potter and the Sorcerer\'s Stone', 'J.K. Rowling', 'A young boy discovers he is a wizard and attends a magical school.', 'Fantasy', '1997-06-26', false),
('The Chronicles of Narnia', 'C.S. Lewis', 'A series of seven fantasy novels set in the magical land of Narnia.', 'Fantasy', '1950-10-16', false),
('The Alchemist', 'Paulo Coelho', 'A young shepherd embarks on a journey to discover the meaning of life.', 'Adventure', '1988-05-01', false),
('The Kite Runner', 'Khaled Hosseini', 'A story of friendship and redemption set in Afghanistan.', 'Historical Fiction', '2003-05-29', false),
('The Shining', 'Stephen King', 'A haunted hotel and the terrifying events that occur there.', 'Horror', '1977-01-28', false),
('The Hunger Games', 'Suzanne Collins', 'A dystopian novel about a society that holds an annual deadly competition.', 'Science Fiction', '2008-09-14', true),
('Lord of the Flies', 'William Golding', 'A novel about a group of boys stranded on an island and their descent into savagery.', 'Fiction', '1954-09-17', false),
('The Book Thief', 'Markus Zusak', 'A young girl in Nazi Germany finds solace in books and words during World War II.', 'Historical Fiction', '2005-03-14', false),
('The Great Expectations', 'Charles Dickens', 'The coming-of-age story of Pip and his experiences with wealth and class.', 'Classic', '1861-08-01', false),
('Little Women', 'Louisa May Alcott', 'A story about the four March sisters and their lives during the American Civil War.', 'Historical Fiction', '1868-09-30', false),
('Wuthering Heights', 'Emily Brontë', 'A passionate and tragic love story set on the Yorkshire moors.', 'Romance', '1847-12-01', false),
('War and Peace', 'Leo Tolstoy', 'A historical novel about Napoleon’s invasion of Russia and the impact on Russian society.', 'Historical Fiction', '1869-03-01', false),
('Jane Eyre', 'Charlotte Brontë', 'A gothic novel about the life of an orphaned girl and her experiences with love.', 'Romance', '1847-10-16', false),
('The Picture of Dorian Gray', 'Oscar Wilde', 'A philosophical novel about a man who remains youthful while his portrait ages.', 'Gothic', '1890-06-01', false),
('Frankenstein', 'Mary Shelley', 'A gothic novel about a scientist who creates a living being from body parts.', 'Horror', '1818-01-01', false),
('Dracula', 'Bram Stoker', 'A gothic horror novel about Count Dracula and his attempts to move from Transylvania to England.', 'Horror', '1897-05-26', false),
('Fahrenheit 451', 'Ray Bradbury', 'A dystopian novel about a future where books are banned and burned.', 'Dystopian', '1953-10-19', false),
('The Secret Garden', 'Frances Hodgson Burnett', 'A novel about a young girl who discovers a hidden garden that changes her life.', 'Children\'s Literature', '1911-08-01', false),
('The Outsiders', 'S.E. Hinton', 'A story about teenage rebellion and the struggles of growing up.', 'Young Adult', '1967-04-24', false),
('The Road', 'Cormac McCarthy', 'A post-apocalyptic novel about a father and son surviving in a desolate world.', 'Dystopian', '2006-09-26', true),
('The Maze Runner', 'James Dashner', 'A group of teens must navigate a deadly maze and uncover the truth behind their situation.', 'Science Fiction', '2009-10-06', false),
('The Martian', 'Andy Weir', 'A story about an astronaut stranded on Mars trying to survive and return to Earth.', 'Science Fiction', '2011-02-11', false),
('Gone with the Wind', 'Margaret Mitchell', 'A story of love, war, and survival set during the American Civil War.', 'Historical Fiction', '1936-06-30', false),
('The Handmaid\'s Tale', 'Margaret Atwood', 'A dystopian novel about a woman living in a totalitarian society that controls women\'s reproductive rights.', 'Dystopian', '1985-08-01', false),
('The Call of the Wild', 'Jack London', 'A novel about a dog’s journey to survive in the harsh wilderness.', 'Adventure', '1903-01-01', false),
('Les Misérables', 'Victor Hugo', 'A historical novel set during the French Revolution, focusing on justice and redemption.', 'Historical Fiction', '1862-01-01', false),
('The Silence of the Lambs', 'Thomas Harris', 'A psychological horror novel about an FBI agent and the notorious Hannibal Lecter.', 'Thriller', '1988-08-01', false),
('The Hitchhiker\'s Guide to the Galaxy', 'Douglas Adams', 'A comedic science fiction series about a man who is whisked away on an intergalactic adventure.', 'Science Fiction', '1979-10-12', false),
('The Princess Bride', 'William Goldman', 'A fairy tale adventure story filled with romance, action, and wit.', 'Fantasy', '1973-04-09', false),
('A Tale of Two Cities', 'Charles Dickens', 'A historical novel set during the French Revolution, exploring themes of resurrection and sacrifice.', 'Historical Fiction', '1859-04-30', false),
('Catch-22', 'Joseph Heller', 'A satirical novel about the absurdities of war and military life.', 'Satire', '1961-11-10', false),
('Ender\'s Game', 'Orson Scott Card', 'A young boy is recruited to fight an alien race in a futuristic war.', 'Science Fiction', '1985-01-15', false),
('The Color Purple', 'Alice Walker', 'A story about the struggles and triumphs of African-American women in the early 20th century.', 'Historical Fiction', '1982-03-01', false),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A mystery thriller about a journalist and a hacker who uncover a powerful conspiracy.', 'Thriller', '2005-08-01', false);
